biblio/urls.py
from django.urls import path

from .views.authors import author_detail, author_list
from .views.book_types import book_type_detail, book_type_list
from .views.books import book_list, book_detail
from .views.categories import category_list, category_detail
from .views.editions import edition_detail, edition_list
from .views.series import series_list, series_detail
from .views.home import index
from .views.tools import book_create_views


app_name = 'biblio'
urlpatterns = [
    path('books/<int:book_id>', book_detail, name='book_detail'),
    path('books/', book_list, name='book_list'),

    path('authors/<int:author_id>', author_detail, name='author_detail'),
    path('authors/', author_list, name='author_list'),

    path('series/<int:series_id>', series_detail, name='series_detail'),
    path('series/', series_list, name='series_list'),

    path('book-types/<int:book_type_id>', book_type_detail, name='book_type_detail'),
    path('book-types/', book_type_list, name='book_types_list'),

    path('categories/<int:category_id>', category_detail, name='category_detail'),
    path('categories/', category_list, name='category_list'),

    path('editions/<int:edition_id>', edition_detail, name='edition_detail'),
    path('editions/', edition_list, name='edition_list'),

    path('book/create', book_create_views, name='book_create'),

    path('', index, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('collection/', include('biblio.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblio/models/authors.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse


class AuthorType(models.Model):
    """
    scenariste, dessinateur, coloriste ...
    """
    slug = models.SlugField(max_length=250)
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('biblio:author_type_detail', args=[self.id])


class Author(models.Model):
    """
    Auteur/dessinateur (...) d'un livre
    """
    name = models.CharField(max_length=250)
    #first_name = models.CharField(max_length=250, blank=True, null=True)
    type = models.ForeignKey(AuthorType, on_delete=models.DO_NOTHING, related_name="author")

    def __str__(self):
        return f"{self.name}  ({self.type})"

    def get_absolute_url(self):
        return reverse('biblio:author_detail', args=[self.id])

biblio/models/book_types.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse


class BookType(models.Model):
    """
    Manga, BD, Roman...
    """
    slug = models.SlugField(max_length=250)
    name = models.CharField(max_length=500)

    def __str__(self):
        return f"Type :  {self.name}"

    def get_absolute_url(self):
        return reverse('biblio:book_type_detail', args=[self.id])

biblio/models/books.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse

from biblio.models.authors import Author
from biblio.models.editions import Edition
from biblio.models.categories import Category
from biblio.models.book_types import BookType
from biblio.models.series import Series


class Book(models.Model):
    slug = models.SlugField(max_length=250)
    title = models.CharField(max_length=500)
    series = models.ForeignKey(Series, on_delete=models.DO_NOTHING, blank=True, null=True, related_name="book")
    edition_date = models.DateField(blank=True, null=True)
    resume = models.TextField(blank=True, null=True)
    image_file = models.ImageField(blank=True, null=True, upload_to="images/books/")
    image_url = models.URLField(blank=True, null=True)
    isbn = models.CharField(max_length=13, blank=True, null=True)
    authors = models.ManyToManyField(Author)
    edition = models.ForeignKey(Edition, on_delete=models.DO_NOTHING, blank=True, null=True, related_name="book")
    categories = models.ManyToManyField(Category)
    type = models.ForeignKey(BookType, on_delete=models.DO_NOTHING, related_name="book")
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']


    def __str__(self):
        return f"Livre :  {self.title}"

    def get_absolute_url(self):
        return reverse('biblio:book_detail', args=[self.id])

    @property
    def image(self):
        """
        S'il n'y a pas de fichier image uploadé, on regarde s'il existe une url d'image à afficher
        :return:
        """
        img = self.image_url
        if self.image_file:
            img = self.image_file.url
        return img

biblio/models/categories.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """
    aventure, documentaire, fantastique ...
    """
    slug = models.SlugField(max_length=250)
    name = models.CharField(max_length=500)

    def __str__(self):
        return f"Catégorie :  {self.name}"

    def get_absolute_url(self):
        return reverse('biblio:category_detail', args=[self.id])

biblio/models/editions.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse


class Edition(models.Model):
    """
    Le nom de l'editeur d'un livre (ie: Casterman)
    """
    slug = models.SlugField(max_length=250)
    name = models.CharField(max_length=500)

    def __str__(self):
        return f"Edition :  {self.name}"

    def get_absolute_url(self):
        return reverse('biblio:edition_detail', args=[self.id])

biblio/models/series.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse


class Series(models.Model):
    """
    Detail d'une série.
    Permet de relier les livres d'une même série
    par exemple : La série "Tintin", comporte 24 livres (Tintin en Amérique, On a marché sur la lune ...)
    """
    slug = models.SlugField(max_length=250)
    title = models.CharField(max_length=500)
    volumes_number = models.IntegerField()
    is_ended = models.BooleanField(default=False)
    resume = models.TextField(blank=True, null=True)
    image_file = models.ImageField(blank=True, null=True, upload_to="images/series/")
    image_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"Série :  {self.title}"

    def get_absolute_url(self):
        return reverse('biblio:series_detail', args=[self.id])

    @property
    def image(self):
        """
        S'il n'y a pas de fichier image uploadé, on regarde s'il existe une url d'image à afficher
        :return:
        """
        img = self.image_url
        if self.image_file:
            img = self.image_file.url
        return img

biblio/forms.py
from django import forms


class IsbnForm(forms.Form):
    """
    ISBN field to add books
    """
    isbn = forms.CharField(
            label='ISBN',
            widget=forms.TextInput(attrs={'placeholder': 'ISBN'})
    )

class UploadFileForm(forms.Form):
    """
    Upload field to import csv
    """
    file = forms.FileField()

biblio/views/authors.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from biblio.models import Author


@login_required
def author_detail(request, author_id):
    """
    Page détail d'un auteur
    Affiche les informations de l'auteur ainsi que les livres dont il est l'auteur
    """
    author = get_object_or_404(Author, pk=author_id)

    return render(request, "biblio/default_detail.html", {'obj': author})


@login_required
def author_list(request):
    """
    Liste tous les auteurs de la collection
    """
    authors = Author.objects.all()

    return render(
        request, "biblio/default_list.html",
        {
            'objects': authors,
            'page_title': 'Auteurs'
        }
    )

biblio/views/book_types.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from biblio.models import BookType


@login_required
def book_type_detail(request, book_type_id):
    """
    Page détail d'un BookType
    Affiche les livres d'un BookType en particulier
    """
    book_type = get_object_or_404(BookType, pk=book_type_id)

    return render(request, "biblio/default_detail.html", {'obj': book_type})


@login_required
def book_type_list(request):
    """
    Liste tous les BookType
    """
    book_types = BookType.objects.all()

    return render(
        request, "biblio/default_list.html",
        {
            'objects': book_types,
            'page_title': 'Types'
        }
    )

biblio/views/books.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from biblio.models import Book


@login_required
def book_detail(request, book_id):
    """
    Page de détail d'un livre
    """
    book = get_object_or_404(Book, pk=book_id)

    return render(request, "biblio/book_detail.html", {'book': book})


@login_required
def book_list(request):
    """
    Liste tous les livres de la collection
    """

    books = Book.objects.all()
    ordering_fields = ('title', 'authors', 'series', 'create_date')
    field_name = None

    if 'filter' in request.GET:
        field_name = order = request.GET['filter']

        if field_name in ordering_fields:
            if field_name == 'series':
                order = '-series'
            if field_name == 'create_date':
                order = '-create_date'
            books = books.order_by(order)

    if 'q' in request.GET:
        q = request.GET['q']
        books = books.filter(
            Q(title__contains=q)
            | Q(authors__name__contains=q)
            | Q(series__title__contains=q)
            | Q(categories__name__contains=q)
            | Q(type__name__contains=q)
            | Q(edition__name__contains=q)
        ).distinct()

    paginator = Paginator(books, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "biblio/book_list.html", {'books': page_obj, 'filter': field_name})

biblio/views/categories.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from biblio.models import Category


@login_required
def category_detail(request, category_id):
    """
    Page détail d'une catégorie
    Affiche les livres d'une catégorie en particulier
    """
    category = get_object_or_404(Category, pk=category_id)

    return render(request, "biblio/default_detail.html", {'obj': category})


@login_required
def category_list(request):
    """
    Liste toutes les catégories
    """
    categories = Category.objects.all()

    return render(
        request, "biblio/default_list.html",
        {
            'objects': categories,
            'page_title': 'Catégories'
        }
    )

biblio/views/editions.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from biblio.models import Edition


@login_required
def edition_detail(request, edition_id):
    """
    Page détail d'une catégorie
    Affiche les livres d'une catégorie en particulier
    """
    edition = get_object_or_404(Edition, pk=edition_id)

    return render(request, "biblio/default_detail.html", {'obj': edition})


@login_required
def edition_list(request):
    """
    Liste toutes les catégories
    """
    editions = Edition.objects.all()

    return render(
        request, "biblio/default_list.html",
        {
            'objects': editions,
            'page_title': 'Éditions'
        }
    )

biblio/views/home.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from biblio.models import Book


@login_required
def index(request):
    """ Page d'accueil de l'application biblio """

    last_books_add = Book.objects.order_by()[:5]

    return render(request, "biblio/home.html", {'books': last_books_add})

biblio/views/series.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from biblio.models import Series


@login_required
def series_detail(request, series_id):
    """
    Page détail d'une série
    Affiche les informations de la serie ainsi que les livres qu'elle contient
    """
    series = get_object_or_404(Series, pk=series_id)

    return render(request, "biblio/default_detail.html", {'obj': series})


@login_required
def series_list(request):
    """
    Liste toutes les séries
    """
    series = Series.objects.all()

    return render(
        request, "biblio/default_list.html",
        {
            'objects': series,
            'page_title': 'Collections/Series'
        }
    )

biblio/views/tools.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from ..forms import IsbnForm
from ..tools import book_create, get_data_from_google_api, DATA_ORIGIN_GOOGLE_API


@login_required
def book_create_views(request):

    form = IsbnForm()

    if request.method == 'POST':
        form = IsbnForm(request.POST)

        if form.is_valid():
            isbn = form.cleaned_data['isbn']

            data = get_data_from_google_api(isbn)
            book, create = book_create(data, data_origin=DATA_ORIGIN_GOOGLE_API)

            return render(request, "biblio/form_isbn.html", {
                'form': form,
                'book': book,
                'is_created': create
            })

    return render(request, "biblio/form_isbn.html", {'form': form})

biblio/templates/biblio/author_detail.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>{{ author}}</h3>

    <ul>
        {% for book in author.book_set.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock biblio_content %}

biblio/templates/biblio/author_list.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Auteurs</h3>
    <ul>
    {% for author in authors %}
        <li><a href="{{ author.get_absolute_url }}">{{ author }}</a></li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}

biblio/templates/biblio/base.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <h1>Projet Bibliotheque</h1>
        <ul class="navbar">
            <li><a href="{% url 'biblio:home' %}">Home</a></li>
            <li><a href="{% url 'biblio:book_list' %}">Books</a></li>
            <li><a href="{% url 'biblio:author_list' %}">Authors</a></li>
            <li><a href="{% url 'biblio:series_list' %}">Collections/Séries</a></li>
            <li><a href="{% url 'biblio:book_types_list' %}">Types</a></li>
            <li><a href="{% url 'biblio:category_list' %}">Categories</a></li>
            <li><a href="{% url 'biblio:edition_list' %}">editions</a></li>
        </ul>
        {% block biblio_content %}{% endblock %}
    </div>
{% endblock content %}

biblio/templates/biblio/book_list.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <ul>
    {% for book in books %}
        <li><a href="{% url 'biblio:book_detail' book.id %}">{{ book }}</a></li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}

biblio/templates/biblio/book_type_detail.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Type : {{ book_type.name }}</h3>

    <ul>
        {% for book in book_type.book.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock biblio_content %}

biblio/templates/biblio/book_type_list.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Types</h3>
    <ul>
    {% for type in book_types %}
        <li><a href="{{ type.get_absolute_url }}">{{ type.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}

biblio/templates/biblio/category_detail.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Catégorie : {{ category.name }}</h3>

    <ul>
        {% for book in category.book_set.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock biblio_content %}

biblio/templates/biblio/category_list.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Catégories</h3>
    <ul>
    {% for category in categories %}
        <li>
            <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}

biblio/templates/biblio/edition_detail.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Edition : {{ edition.name }}</h3>

    <ul>
        {% for book in edition.book.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock biblio_content %}

biblio/templates/biblio/edition_list.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Editions</h3>
    <ul>
    {% for edition in editions %}
        <li><a href="{{ edition.get_absolute_url }}">{{ edition.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}

biblio/templates/biblio/form_isbn.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
   <h2>Google Book</h2>

    <form action="." method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">go</button>
    </form>

    {% if is_created %}
        <p>Le livre a été créer avec succès</p>
    {% else %}
        <p>Le livre existe déjà</p>
    {% endif %}

    {{ book }}

{% endblock biblio_content %}

biblio/templates/biblio/home.html
{% extends "biblio/base.html" %}

{% block biblio_content %}

    <h3>Derniers livres</h3>
    <p>5 derniers livres ajoutés dans la collection</p>
    <ul>
    {% for book in books %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}

biblio/templates/biblio/series_detail.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Collection/Series : {{ series.title }}</h3>

    <ul>
        {% for book in series.book.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>

{% endblock biblio_content %}

biblio/templates/biblio/series_list.html
{% extends "biblio/base.html" %}

{% block biblio_content %}
    <h3>Collections/Series</h3>
    <ul>
    {% for serie in series %}
        <li>
            <img src="{{ serie.image }}" width="80px">
            <a href="{{ serie.get_absolute_url }}">{{ serie.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock biblio_content %}