biblio/urls.py
from django.urls import path

from .views.authors import author_detail, author_list
from .views.book_types import book_type_detail, book_type_list
from .views.books import book_list, book_detail
from .views.categories import category_list, category_detail
from .views.editions import edition_detail, edition_list
from .views.series import series_list, series_detail
from .views.home import index
from .views.tools import book_create_views


app_name = 'biblio'
urlpatterns = [
    path('books/<int:book_id>', book_detail, name='book_detail'),
    path('books/', book_list, name='book_list'),

    path('authors/<int:author_id>', author_detail, name='author_detail'),
    path('authors/', author_list, name='author_list'),

    path('series/<int:series_id>', series_detail, name='series_detail'),
    path('series/', series_list, name='series_list'),

    path('book-types/<int:book_type_id>', book_type_detail, name='book_type_detail'),
    path('book-types/', book_type_list, name='book_types_list'),

    path('categories/<int:category_id>', category_detail, name='category_detail'),
    path('categories/', category_list, name='category_list'),

    path('editions/<int:edition_id>', edition_detail, name='edition_detail'),
    path('editions/', edition_list, name='edition_list'),

    path('book/create', book_create_views, name='book_create'),

    path('', index, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('collection/', include('biblio.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblio/views/home.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from biblio.models import Book


@login_required
def index(request):
    """ Page d'accueil de l'application biblio """

    last_books_add = Book.objects.order_by()[:5]

    return render(request, "biblio/home.html", {'books': last_books_add})

templates/home.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <!-- Nb livre total Card -->
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Nb livres total</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ books.count }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                Derniers livres ajoutés
                            </div>
                            <ul class="mt-2">
                            {% for book in last_books %}
                                <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/layout.html
{% load sekizai_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyBiblio</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" >
    <link href="/static/core/css/style.css" rel="stylesheet" >
</head>

<body>

    {% include "menu.html" %}

    <div class="container pt-5">
        {% block content %}{% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% render_block "js" %}
</body>
</html>

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand" href="{% url 'home' %}">MyBiblio</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item {% if request.path == '/' %}active{% endif %}">
        <a class="nav-link" href="{% url 'home' %}">Accueil <span class="sr-only">(current)</span></a>
      </li>


      <li class="nav-item dropdown {% if '/collection/' in request.path %}active{% endif %}"">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Collections
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'biblio:book_list' %}">Livres</a>
            <a class="dropdown-item" href="{% url 'biblio:author_list' %}">Auteurs</a>
            <a class="dropdown-item" href="{% url 'biblio:series_list' %}">Collections/Séries</a>
        </div>
      </li>
    </ul>

    <a class="btn btn-outline-success mr-2 my-sm-0" href="{% url 'biblio:book_create' %}">Ajouter un livre</a>
    <form class="form-inline my-2 my-lg-0" action="{% url 'biblio:book_list' %}" method="get" >
      <input class="form-control mr-sm-2" type="search" placeholder="Rechercher" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Go</button>
    </form>
  </div>
</nav>